services:
  dpm-environment:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dpm-environment
    container_name: dpm-dev
    hostname: dpm-docker
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace
      - dpm-config:/root/.dpm
      - dpm-apt-cache:/var/cache/apt
      - dpm-cache:/var/cache/dpm
    environment:
      - TERM=xterm-256color
      - DPM_DOCKER_ENV=1
      - PYTHONPATH=/workspace
    networks:
      - dpm-network
    command: tail -f /dev/null

volumes:
  dpm-config:
  dpm-apt-cache:
  dpm-cache:

networks:
  dpm-network:
    driver: bridge