version: '3.8'

services:
  dpm-environment:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dpm-environment
    container_name: dpm-dev
    hostname: dpm-docker
    stdin_open: true
    tty: true
    volumes:
      # Mount source code for development (live editing)
      - ..:/workspace
      # Persist DPM configuration
      - dpm-config:/root/.dpm
      # Persist package cache
      - dpm-apt-cache:/var/cache/apt
      - dpm-cache:/var/cache/dpm
      # Mount Docker socket for advanced testing (optional)
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TERM=xterm-256color
      - DPM_DOCKER_ENV=1
      - PYTHONPATH=/workspace
    networks:
      - dpm-network
    # Keep container running
    command: tail -f /dev/null

volumes:
  dpm-config:
  dpm-apt-cache:
  dpm-cache:

networks:
  dpm-network:
    driver: bridge